name: Create Release

on:
  push:
    branches:
      - master
      - pre
      - exp
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.1.3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup npm for npmjs
        uses: actions/setup-node@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: Publish to npmjs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./scripts/release_npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup npm for GPR
        uses: actions/setup-node@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GPR
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./scripts/release_gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
